project:
  type: website

website:
  title: "Alex Zhong"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example analysis

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



