project:
  type: website

website:
  title: "Alex Zhong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: example_analysis.qmd
        text: Example analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



