---
title: "About me"
---

## Education

**Sc.M. in Biostatistics** | Johns Hopkins Bloomberg School of Public Health *(current)*

**B.S. in Quantitative Sciences** | Emory University

**Associate of Arts** | Oxford College of Emory University

## Experience
**University of Michigan SPH** | [SIBS](https://sph.umich.edu/bdsi/){target="_blank"} Research Student | June - July 2022

- I applied SIR, SEIR, and eSIR models to predict the course of the COVID-19 pandemic in Mexico using. Our team also designed an interactive [Shiny web app](https://alxhzhong.shinyapps.io/COVID19_Mexico/){.external target="_blank"} (which is currently down but will be up soon!).

**Connecticut Agricultural Experiment Station** | Intern | June - August 2021

- Through the [DDCSP program at YSE](https://conservationscholars.yale.edu/doris-duke-conservation-scholars){target="_blank"}, I helped with programming the data analysis on a project quantifying PFAS pollutants in dried blood spot samples.

## Personal hobbies
In my free time, I enjoy baking, solving [contest crosswords](https://www.wsj.com/public/resources/documents/crosswordcontestguide.pdf){target="_blank"}, and catching up on the latest [podcast](https://publichealth.jhu.edu/headlines/public-health-on-call-podcast){target="_blank"} episode.
